apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-daemonset
  labels:
    env: prod
    app: nginx
    server: webserver
spec:
  selector:
    matchLabels:
      application: nginx-daemon
  template:
    metadata:
      labels:
        application: nginx-daemon
    spec:
      containers:
        - name: nginx-container
          image: nginx:1.24
