apiVersion: v1
kind: Pod
metadata:
  name: multi-volume-emptydir
spec:
  containers:
    - name: nginx-container
      image: nginx
      volumeMounts:
        - name: vol-emptydir
          mountPath: /data
    - name: busybox
      image: busybox
      command: ["/bin/sh"]
      args: ["-c", "while true; do wget -q -O- http://localhost; sleep 2; done"]
      volumeMounts:
        - name: vol-emptydir
          mountPath: /data
  volumes:
    - name: vol-emptydir
      emptyDir: {}
