apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-volume-hostpath
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-container
        image: nginx
        volumeMounts:
          - name: vol-hostpath
            mountPath: /data
      volumes:
      - name: vol-hostpath
        hostPath:
          path: /mydata
