apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deploy
spec:
  replicas: 1
  selector: 
    matchLabels:
      name: mongodb
  template:
    metadata: 
      labels:
        name: mongodb
    spec:
      containers:
        - name: mongodb-container
          image: mongo:latest
          ports:
            - containerPort: 27017
          env:
            - name: MONGODB_INITDB_ROOT_USERNAME
              value: "admin"
              #              valueFrom: 
              # secretKeyRef:
              #   name: mongo-db-secrets
              #   key: mongodb-root-username
            - name: MONGODB_INITDB_ROOT_PASSWORD
              value: "root"
              #              valueFrom:
              # secretKeyRef:
              #   name: mongo-db-secrets
              #   key: mongodb-root-password

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    name: mongodb
  ports:
   - port: 27017
     protocol: TCP
     targetPort: 27017
