apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-express
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mongodb-express
  template:
    metadata:
  
      labels: 
        name: mongodb-express
    spec:
      containers:
        - name: mongo-express
          image: mongo-express:latest
          ports:
            - containerPort: 8081
          env:
           - name: ME_CONFIG_BASICAUTH_USERNAME
             value: "admin"
           - name: ME_CONFIG_BASICAUTH_PASSWORD
             value: "password"
           - name: ME_CONFIG_MONGODB_ADMINUSERNAME
             value: "admin"
               #             valueFrom:
               #               secretKeyRef:
               # name: mongo-db-secrets
               # key: mongodb-root-username
           - name: ME_CONFIG_MONGODB_ADMINPASSWORD
             value: "root"
               #             valueFrom:
               #               secretKeyRef:
               #                 name: mongo-db-secrets
               #                 key: mongodb-root-password
           - name: ME_CONFIG_MONGODB_SERVER
             value: "mongodb-service"

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-express-service
spec:
  type: NodePort
  selector:
    name: mongodb-express
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 8081








#           - name: ME_CONFIG_MONGODB_ADMINUSERNAME
               #             valueFrom:
               #               secretKeyRef:
               # name: mongo-db-secrets
               # key: mongodb-root-username
               #           - name: ME_CONFIG_MONGODB_ADMINPASSWORD
               #             valueFrom:
               #               secretKeyRef:
               #                 name: mongo-db-secrets
               #                 key: mongodb-root-password
