apiVersion: v1
kind: Pod
metadata:
  name: pvc-pod
spec:
  containers:
    - name: mysql
      image: mysql
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "mypassword"
      volumeMounts:
        - name: storage
          mountPath: "/var/lib/mysql"
  volumes:
    - name: storage
      persistentVolumeClaim:
        claimName: my-pvc
